### ISSUE TITLE
请问这个项目的开发环境怎样搭建

### ISSUE THREAD

**Issue by lvxinzhi** [nenoxj/swing-helper#2]
阁下，您好
      感觉你这个项目挺好的。请问你的这个开发环境是什么？JDK用的是那个版本，我用idea导入后报好多错误，方便的话给邮件回复一下，我的邮箱是1926646575@qq.com

**Comment by nenoxj** [comment]
java8&nbsp; 202








邢杰
***@***.***



&nbsp;
